In [1]:
print("dhwed")

dhwed


In [3]:
# write a python program to find the given number is even or odd
num = int(input("Enter a number: "))
if num % 2 == 0:
    print("num is even")
else:
    print("num is odd")

num is odd


In [ ]:
# write a python program to find the sum of first n natural numbers
n = 
n = n+1
print(n)

1.0


In [18]:
s = 0
for i in range(10):
    s = s+i
print(s)




45


In [19]:
# find the sum of first n even numbers
n = int(input("enter n: "))
s = 0
for i in range(0,n+1,2):
    s = s+i
print(s)


2550


In [24]:
s = 0
for i in range(-10,-1):
    s = s+i
print(s)

-54


In [31]:
# find the sum of first 10 odd negative numbers
s = 0
for i in range(-11,0, 2):
    s = s+i
print(s)

-36


In [46]:
a = "srivenkateshwaracollege"
# for i in a:
#     print(i)
a[17:25]

'ollege'

In [47]:
# print the even alphabets
a[1::2]

'rvnaehaaolg'

In [ ]:
# convert the even alphabets into uppercase
a = "srivenkateshwaracollege"


In [ ]:
if statement:
    print()
else:
    print()

if statement:
    print()
elif statement:
    print()
elif statement:
    print()
else:
    print()

# for loop
for i in range(10):
    print(i)

sequence = "srivenkateshwaracollege"
for i in sequence:
    print(i)


In [5]:
# while loop
i = 0
while i<10:
    print(i)
    i = i+1


0
1
2
3
4
5
6
7
8
9


In [14]:
# print the even number upto 10 using while loop
i = 0
s = 0
while i<10:
    # print(i)
    s = s+i
    i = i+2
print(s)

20


In [ ]:
# sum of digits in a given number using while loop 
# input ---> 1234
# output ---> 10 
num = int(input("enter a number: "))
s = 0
while num>0:
    digit = num%10
    s = s+ digit
    num = num//10
print(s)    

45


In [23]:
#product of digits in a given number using while loop
# input ---> 1234
# output ---> 24
num = int(input("enter a number: "))
prod = 1
while num>0:
    digit = num%10
    prod = prod* digit
    num = num//10
print(prod) 

24


In [26]:
# find the sum of digits in a given number using for loop
n = input("enter a number:  ")
import time
start = time.perf_counter()
s = 0
for i in n:
    s = s+int(i)
print(s)
end = time.perf_counter()
print("total time: ",end - start)


45
total time:  0.0006588459982594941


In [28]:
# print the factors of a given number
# input ---> 20
# output ---> 1,2,4,5,10,20
num = int(input("enter a number: "))
for i in range(1,num+1):
    if num%i == 0:
        print(i)

1
2
4
5
10
20


In [48]:
# int 
a = 5
#  string
a = 'sjdhggd'
#  float
a = 5.67
# , bool
1<10
# list
l = [1,2,3,4,5, 'dgs', 'sgfs']
#  tuple
t = (5,5,6,1)  
# , set
# unordered collection of unique elements
s = {1,2,3,4,5,5,5,5,6}

#  dictionary
d = {'name':'srivenkateshwaracollege',
      'location':'bengaluru', 'estd': 1966}

In [50]:
d.values()

dict_values(['srivenkateshwaracollege', 'bengaluru', 1966])

In [1]:
# find the mean of values available in the below list using for loop
l = [1,2,3,4,5,6,7,8,9]
total = 0
for i in l:
    total += i
mean = total / len(l)
print(mean)

5.0


In [4]:
# create a function called mean() to find the mean of values available in the below list
def mean(l):
    total = 0
    for i in l:
        total += i
    mean = total / len(l)
    return mean
li = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
print(mean(li))

8.0


In [6]:
mean(l)

5.0

In [10]:
# capitalise the first and last alphabet of every word in a sentence
# input -----> inidia is my country
#output -----> IndiA IS MY CountrY
def capitalize_first_last(sentence):
    words = sentence.split()
    cap_words = []
    for word in words:
        cap_word = word[0].upper() + word[1:-1] + word[-1].upper()
        cap_words.append(cap_word)
    return ' '.join(cap_words)
sentence = input("enter a sentence: ")
print(capitalize_first_last(sentence))
    


KsdufH EkjfH SejfH


In [ ]:
# python function to find the factors of a given number
# input ---> 20
# output ---> [1,2,4,5,10,20]
n = int(input("enter a number: "))
def factors(n):
    fact = []
    for i in range(1,n+1):
        if n%i == 0:
            fact.append(i)
    return fact
print(factors(n))


[1, 2, 4, 5, 10, 20]


In [16]:
# find the given number is prime or not using factors()
def isPrime(n):
    if factors(n) == [1,n]:
        return True
    else:
        return False
n = int(input("enter a number: "))
print(isPrime(n))

True


In [17]:
# find the sum of prime numbers upto 100 using isPrime()
s = 0
for i in range(1, 101):
    if isPrime(i):
        s = s+i
print(s)

1060


In [18]:
pwd

'/home/kailas/projects'

In [ ]:
# data science libraries
# numpy
# pandas
# matplotlib
# seaborn
# scikit-learn
# tensorflow
# pytorch   


In [4]:
# creating a numpy array from a list
import numpy as np
l = [1,2,3,4,5]
arr = np.array(l)
print(arr)
print(type(arr))
print("shape: ", arr.shape)
print("dimesnsion: ",arr.ndim)
print("size", arr.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
shape:  (5,)
dimesnsion:  1
size 5


In [5]:
# create a numpy and find it's shape, dimension and size
a = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(a)
print(arr)
print("shape: ", arr.shape)
print("dimension: ", arr.ndim)  
print("size: ", arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape:  (3, 3)
dimension:  2
size:  9


In [ ]:
# memory consumption of a list and array
import sys
li = [1,2,3,4,5,6,7,8,9,0]
print("memory cons single elem",sys.getsizeof(li[0]))
print("totalmemory cons:",len(li)*sys.getsizeof(li[0]))

memory cons single elem 28
total memory cons: 280


In [ ]:
import numpy as np
arr = np.array(li)
print("memory cons single ele: ", arr.itemsize)
print("total memory cons: ",arr.itemsize* arr.size)

memory cons sigle ele:  8
total memory cons:  80


In [8]:
pwd

'/home/kailas/projects'